version: "3.8"
services:
    app:
        build:
            context: .
        volumes:
            - .:/disney-plus-clone
        ports: 
            - 3000:3000
        image: app:react
        container_name: react-disney-plus-clone
        command: yarn start